added compose & action

diff --git a/.github/workflows/ljfcloud-setup.yml b/.github/workflows/ljfcloud-setup.yml
--- a/.github/workflows/ljfcloud-setup.yml
+++ b/.github/workflows/ljfcloud-setup.yml
@@ -1,13 +1,13 @@
 
-name: LJF Cloud Network Setup
+name: LJF Cloud Setup
 on:
   workflow_dispatch:
   push:
     branches:
       - main
-      - ljfcloud-server-add
+      - duckdns-add
     paths:
-      - '.github/workflows/install-docker-ljfcloud.yml'    
+      - '.github/workflows/ljfcloud-setup.yml'    
 jobs:
   Update_Security_Lists:
     runs-on: ubuntu-latest
@@ -402,3 +402,125 @@ jobs:
           sudo wg-quick down ./wg0.conf
           sudo wg show   
 
+  add_DuckDNS_updaterr:
+    runs-on: ubuntu-latest
+    needs: install_docker_and_add_to_portainer
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v4
+
+      - name: Install WireGuard
+        run: |
+          sudo apt-get install -y wireguard || (sudo apt-get update && sudo apt-get install -y wireguard)  
+          
+      - name: Write WireGuard config
+        run: |
+          echo "${{ secrets.WG_CONFIG }}" > wg0.conf
+          
+      - name: Bring up VPN on runner
+        run: |
+          sudo wg-quick up ./wg0.conf
+          sudo wg show  
+
+      - name: Override system DNS resolver on runner
+        run: |
+          sudo rm /etc/resolv.conf
+          echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
+          
+      - name: Add host key to known_hosts of runner
+        run: |
+          mkdir -p ~/.ssh
+          ssh-keyscan -H ${{ vars.LJFCLOUD_IP }} >> ~/.ssh/known_hosts
+
+      - name: Authenticate to Portainer
+        id: auth
+        run: |
+          RESPONSE=$(curl -X POST "http://${{ vars.RPI4_IP }}:83/api/auth" \
+            -H "Content-Type: application/json" \
+            -d '{
+                 "Username":"${{ vars.APP_USER }}",
+                 "Password":"${{ secrets.APP_PASSWORD }}"
+                 }')
+          TOKEN=$(echo "$RESPONSE" | jq -r '.jwt')
+          echo "token=$TOKEN" >> $GITHUB_OUTPUT
+
+      - name: Get Stack ID (if exists)
+        id: get_stack_id
+        run: |
+          STACKS=$(curl --fail -s -X GET "http://${{ vars.RPI4_IP }}:83/api/stacks" \
+          -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" || echo "")
+
+          STACK_ID=$(echo "$STACKS" | jq -r '.[] | select(.Name=="DuckDNS") | .Id')
+          
+          if [ -z "$STACK_ID" ]; then
+            echo "Stack not found."
+            echo "stack_id=0" >> $GITHUB_OUTPUT
+          else
+            echo "Stack found with ID: $STACK_ID"
+            echo "stack_id=$STACK_ID" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Get Portainer EndpointId
+        id: endpoint
+        run: |
+          RESPONSE=$(curl -s -X GET "http://${{ vars.RPI4_IP }}:83/api/endpoints" \
+            -H "Authorization: Bearer ${{ steps.auth.outputs.token }}")
+          ENDPOINT_ID=$(echo "$RESPONSE" | jq -r '.[] | select(.Name=="ljfcloud-server") | .Id')
+          echo "endpoint_id=$ENDPOINT_ID" >> $GITHUB_OUTPUT
+
+      - name: Create Stack from GitHub
+        if: ${{ steps.get_stack_id.outputs.stack_id == '0' }}
+        run: |
+          echo "Creating stack from GitHub..."
+          RESPONSE=$(curl -v -s -S -X POST "http://${{ vars.RPI4_IP }}:83/api/stacks/create/standalone/repository?endpointId=${{ steps.endpoint.outputs.endpoint_id }}" \
+          -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" \
+          -H "Content-Type: application/json" \
+          -d '{
+               "Name": "DuckDNS",
+               "RepositoryURL": "https://github.com/liamj-f/homelab-setup",
+               "RepositoryReferenceName": "${{ github.ref }}",
+               "ComposeFile": "duckdns-compose.yml",
+               "RepositoryAuthentication": false,
+               "AutoUpdate": {
+                              "forcePullImage": true,
+                              "forceUpdate": true,
+                              "Webhook": "85e9c603-75d0-4e93-969d-dc7641c80d83"
+                             },
+               "Env": [
+                       {
+                       "name":"DUCKDNS_TOKEN",
+                       "value":"${{ secrets.DUCKDNS_TOKEN }}"
+                        }
+               ],
+               "Prune": true,
+               "StackFileVersion": "3"
+              }')
+
+            echo "API Response: $RESPONSE"
+            echo "stack_response=$RESPONSE" >> $GITHUB_OUTPUT
+
+      - name: Update Stack
+        if: ${{ steps.get_stack_id.outputs.stack_id != '0' }}
+        run: |
+          OCI_KEY_BASE64=$(echo "${{ secrets.NETWORKUPDATERSA_API_KEY }}" | base64 -w 0)
+          
+          curl -s -X PUT "http://${{ vars.RPI4_IP }}:83/api/stacks/${{ steps.get_stack_id.outputs.stack_id }}/git/redeploy?endpointId=${{ steps.endpoint.outputs.endpoint_id }}" \
+          -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" \
+          -H "Content-Type: application/json" \
+          -d '{
+               "PullImage": true,
+               "RepositoryReferenceName": "${{ github.ref }}",
+               "repositoryAuthentication": false,
+               "Env": [
+                       {
+                       "name":"DUCKDNS_TOKEN",
+                       "value":"${{ secrets.DUCKDNS_TOKEN }}"
+                        }
+               ],
+               "Prune": true
+              }'
+
+      - name: Bring down VPN
+        run: |
+          sudo wg-quick down ./wg0.conf
+          sudo wg show   
