Duckdns add (#48)
* added compose & action

* rid vars in update stack

* portainer agent update

* Rename Duckdns-compose.yml to duckdns-compose.yml

* lowercase duckdns

* removed unnecessary oci ref

* Changed all workflows to find & match on portainer endpoint & stack id.
Added duckdns and security list updater as separate workflows & composes

* seeing if you can remove webhook guid

* generate new webhook guids for stacks

diff --git a/.github/workflows/mysql-redeploy.yml b/.github/workflows/mysql-redeploy.yml
--- a/.github/workflows/mysql-redeploy.yml
+++ b/.github/workflows/mysql-redeploy.yml
@@ -6,12 +6,22 @@ on:
     paths:
       - 'mysql-compose.yml'
       - '.github/workflows/mysql-redeploy.yml'
-  workflow_dispatch:
   workflow_call:
     inputs:
-      branch_name:
+      host_machine:
+        required: true
+        type: string 
+      subdomain:
         required: true
         type: string
+  workflow_dispatch:
+    inputs:
+      host_machine:
+        required: true
+        type: string 
+      subdomain:
+        required: true
+        type: string  
 
 jobs:
   deploy:
@@ -21,8 +31,8 @@ jobs:
         uses: actions/checkout@v4
       - name: Install WireGuard
         run: |
-          sudo apt-get update
-          sudo apt-get install -y wireguard 
+          sudo apt-get install -y wireguard || (sudo apt-get update && sudo apt-get install -y wireguard)  
+
       - name: Write WireGuard config
         run: |
           echo "${{ secrets.WG_CONFIG }}" > wg0.conf
@@ -49,30 +59,37 @@ jobs:
           TOKEN=$(echo "$RESPONSE" | jq -r '.jwt')
           echo "token=$TOKEN" >> $GITHUB_OUTPUT
 
-      - name: Get Stack ID (if exists)
-        id: get_stack_id
-        run: |
-          STACKS=$(curl --fail -s -X GET "http://${{ vars.RPI4_IP }}:83/api/stacks" \
-          -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" || echo "")
-
-          STACK_ID=$(echo "$STACKS" | jq -r '.[] | select(.Name=="mysql") | .Id')
-          
-          if [ -z "$STACK_ID" ]; then
-            echo "Stack not found."
-            echo "stack_id=0" >> $GITHUB_OUTPUT
-          else
-            echo "Stack found with ID: $STACK_ID"
-            echo "stack_id=$STACK_ID" >> $GITHUB_OUTPUT
-          fi
-
       - name: Get Portainer EndpointId
         id: endpoint
         run: |
           RESPONSE=$(curl -s -X GET "http://${{ vars.RPI4_IP }}:83/api/endpoints" \
             -H "Authorization: Bearer ${{ steps.auth.outputs.token }}")
-          ENDPOINT_ID=$(echo "$RESPONSE" | jq -r '.[] | select(.Name=="e7270-server") | .Id')
+          ENDPOINT_ID=$(echo "$RESPONSE" | jq -r '.[] | select(.Name=="{${{ inputs.host_machine || 'e7270-server'}}}") | .Id')
           echo "endpoint_id=$ENDPOINT_ID" >> $GITHUB_OUTPUT
 
+      - name: Get Stack ID (if exists)
+        id: get_stack_id
+        run: |
+          STACKS=$(curl --fail -s -X GET "http://${{ vars.RPI4_IP }}:83/api/stacks" \
+          -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" || echo "[]")
+
+          # Filter by both Name AND EndpointId
+          STACK_ID=$(echo "$STACKS" | jq -r '.[] | select(.Name=="mysql" and .EndpointId==${{ steps.endpoint.outputs.endpoint_id }}) | .Id')
+          
+          if [ -z "$STACK_ID" ] || [ "$STACK_ID" = "null" ]; then
+            echo "Stack not found for this endpoint."
+            echo "stack_id=0" >> $GITHUB_OUTPUT
+          else
+            echo "Stack found with ID: $STACK_ID"
+            echo "stack_id=$STACK_ID" >> $GITHUB_OUTPUT
+          fi
+          
+      - name: Generate UUID
+        if: ${{ steps.get_stack_id.outputs.stack_id == '0' }}
+        id: uuid
+        run: |
+          echo "::set-output name=uuid::$(uuidgen)"
+      
       - name: Create Stack from GitHub
         if: ${{ steps.get_stack_id.outputs.stack_id == '0' }}
         run: |
@@ -89,7 +106,7 @@ jobs:
                "AutoUpdate": {
                               "forcePullImage": true,
                               "forceUpdate": true,
-                              "Webhook": "d8e18d38-8ade-45b9-a226-7487d6780865"
+                              "Webhook": "${{ steps.uuid.outputs.uuid }}"
                              },
                "Env": [
                        {
diff --git a/.github/workflows/nginx-redeploy.yml b/.github/workflows/nginx-redeploy.yml
--- a/.github/workflows/nginx-redeploy.yml
+++ b/.github/workflows/nginx-redeploy.yml
@@ -7,12 +7,21 @@ on:
       - 'nginx-compose.yml'
       - '.github/workflows/nginx-redeploy.yml'
   workflow_dispatch:
-  workflow_call:
     inputs:
-      branch_name:
+      host_machine:
+        required: true
+        type: string 
+      subdomain:
         required: true
         type: string
-
+  workflow_call:
+    inputs:
+      host_machine:
+        required: true
+        type: string 
+      subdomain:
+        required: true
+        type: string
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -21,8 +30,7 @@ jobs:
         uses: actions/checkout@v4
       - name: Install WireGuard
         run: |
-          sudo apt-get update
-          sudo apt-get install -y wireguard 
+          sudo apt-get install -y wireguard || (sudo apt-get update && sudo apt-get install -y wireguard)  
 
       - name: Write WireGuard config
         run: |
@@ -50,29 +58,36 @@ jobs:
           TOKEN=$(echo "$RESPONSE" | jq -r '.jwt')
           echo "token=$TOKEN" >> $GITHUB_OUTPUT
 
+      - name: Get Portainer EndpointId
+        id: endpoint
+        run: |
+          RESPONSE=$(curl -s -X GET "http://${{ vars.RPI4_IP }}:83/api/endpoints" \
+            -H "Authorization: Bearer ${{ steps.auth.outputs.token }}")
+          ENDPOINT_ID=$(echo "$RESPONSE" | jq -r '.[] | select(.Name=="${{ inputs.host_machine || 'local' }}") | .Id')
+          echo "endpoint_id=$ENDPOINT_ID" >> $GITHUB_OUTPUT
+
       - name: Get Stack ID (if exists)
         id: get_stack_id
         run: |
           STACKS=$(curl --fail -s -X GET "http://${{ vars.RPI4_IP }}:83/api/stacks" \
-          -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" || echo "")
+          -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" || echo "[]")
 
-          STACK_ID=$(echo "$STACKS" | jq -r '.[] | select(.Name=="nginx") | .Id')
+          # Filter by both Name AND EndpointId
+          STACK_ID=$(echo "$STACKS" | jq -r '.[] | select(.Name=="nginx" and .EndpointId==${{ steps.endpoint.outputs.endpoint_id }}) | .Id')
           
-          if [ -z "$STACK_ID" ]; then
-            echo "Stack not found."
+          if [ -z "$STACK_ID" ] || [ "$STACK_ID" = "null" ]; then
+            echo "Stack not found for this endpoint."
             echo "stack_id=0" >> $GITHUB_OUTPUT
           else
             echo "Stack found with ID: $STACK_ID"
             echo "stack_id=$STACK_ID" >> $GITHUB_OUTPUT
           fi
 
-      - name: Get Portainer EndpointId
-        id: endpoint
+      - name: Generate UUID
+        if: ${{ steps.get_stack_id.outputs.stack_id == '0' }}
+        id: uuid
         run: |
-          RESPONSE=$(curl -s -X GET "http://${{ vars.RPI4_IP }}:83/api/endpoints" \
-            -H "Authorization: Bearer ${{ steps.auth.outputs.token }}")
-          ENDPOINT_ID=$(echo "$RESPONSE" | jq -r '.[] | select(.Name=="local") | .Id')
-          echo "endpoint_id=$ENDPOINT_ID" >> $GITHUB_OUTPUT
+          echo "::set-output name=uuid::$(uuidgen)"
 
       - name: Create Stack from GitHub
         if: ${{ steps.get_stack_id.outputs.stack_id == '0' }}
@@ -90,7 +105,7 @@ jobs:
                "AutoUpdate": {
                               "forcePullImage": true,
                               "forceUpdate": true,
-                              "Webhook": "e0ac1738-d609-4ef9-9865-2c73be74fbc0"
+                              "Webhook": "${{ steps.uuid.outputs.uuid }}"                            
                              },
                "Env": [
                        {
@@ -150,13 +165,13 @@ jobs:
         run: |
           TOKEN="${{ steps.token.outputs.token }}"
           declare -A hosts
-          hosts["tplink.14monarch.local"]="192.168.0.1:80"
-          hosts["nginx.14monarch.local"]="${{ vars.RPI4_IP }}:81"
-          hosts["pihole.14monarch.local"]="${{ vars.RPI4_IP }}:82"
-          hosts["portainer.14monarch.local"]="${{ vars.RPI4_IP }}:83"
-          hosts["adminer.14monarch.local"]="${{ vars.RPI4_IP }}:84"
-          hosts["nextcloud.14monarch.local"]="${{ vars.E7270_IP }}:80"
-          hosts["pih0le.14monarch.local"]="${{ vars.RPI0_IP }}:82"
+          hosts["tplink.${{ inputs.subdomain }}.local"]="192.168.0.1:80"
+          hosts["nginx.${{ inputs.subdomain }}.local"]="${{ vars.RPI4_IP }}:81"
+          hosts["pihole.${{ inputs.subdomain }}.local"]="${{ vars.RPI4_IP }}:82"
+          hosts["portainer.${{ inputs.subdomain }}.local"]="${{ vars.RPI4_IP }}:83"
+          hosts["adminer.${{ inputs.subdomain }}.local"]="${{ vars.RPI4_IP }}:84"
+          hosts["nextcloud.${{ inputs.subdomain }}.local"]="${{ vars.E7270_IP }}:80"
+          hosts["pih0le.${{ inputs.subdomain }}.local"]="${{ vars.RPI0_IP }}:82"
           
           for domain in "${!hosts[@]}"; do
             host="${hosts[$domain]}"
@@ -175,6 +190,7 @@ jobs:
                 "enabled": true
               }' | jq
           done
+
       - name: Bring down VPN
         run: |
           sudo wg-quick down ./wg0.conf
diff --git a/.github/workflows/pihole-redeploy.yml b/.github/workflows/pihole-redeploy.yml
--- a/.github/workflows/pihole-redeploy.yml
+++ b/.github/workflows/pihole-redeploy.yml
@@ -7,11 +7,21 @@ on:
       - 'pihole/**'
       - '.github/workflows/pihole-redeploy.yml'
   workflow_dispatch:
-  workflow_call:
     inputs:
-      branch_name:
+      host_machine:
+        required: true
+        type: string 
+      subdomain:
         required: true
         type: string
+  workflow_call:
+    inputs:
+      host_machine:
+        required: true
+        type: string 
+      subdomain:
+        required: true
+        type: string   
         
 jobs:
   deploy:
@@ -21,8 +31,7 @@ jobs:
         uses: actions/checkout@v4
       - name: Install WireGuard
         run: |
-          sudo apt-get update
-          sudo apt-get install -y wireguard
+          sudo apt-get install -y wireguard || (sudo apt-get update && sudo apt-get install -y wireguard)  
           
       - name: Write WireGuard config
         run: |
@@ -60,29 +69,36 @@ jobs:
           TOKEN=$(echo "$RESPONSE" | jq -r '.jwt')
           echo "token=$TOKEN" >> $GITHUB_OUTPUT
 
+      - name: Get Portainer EndpointId
+        id: endpoint
+        run: |
+          RESPONSE=$(curl -s -X GET "http://${{ vars.RPI4_IP }}:83/api/endpoints" \
+            -H "Authorization: Bearer ${{ steps.auth.outputs.token }}")
+          ENDPOINT_ID=$(echo "$RESPONSE" | jq -r '.[] | select(.Name=="${{ inputs.host_machine || 'local' }}") | .Id')
+          echo "endpoint_id=$ENDPOINT_ID" >> $GITHUB_OUTPUT
+
       - name: Get Stack ID (if exists)
         id: get_stack_id
         run: |
           STACKS=$(curl --fail -s -X GET "http://${{ vars.RPI4_IP }}:83/api/stacks" \
-          -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" || echo "")
+          -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" || echo "[]")
 
-          STACK_ID=$(echo "$STACKS" | jq -r '.[] | select(.Name=="pihole") | .Id')
+          # Filter by both Name AND EndpointId
+          STACK_ID=$(echo "$STACKS" | jq -r '.[] | select(.Name=="pihole" and .EndpointId==${{ steps.endpoint.outputs.endpoint_id }}) | .Id')
           
-          if [ -z "$STACK_ID" ]; then
-            echo "Stack not found."
+          if [ -z "$STACK_ID" ] || [ "$STACK_ID" = "null" ]; then
+            echo "Stack not found for this endpoint."
             echo "stack_id=0" >> $GITHUB_OUTPUT
           else
             echo "Stack found with ID: $STACK_ID"
             echo "stack_id=$STACK_ID" >> $GITHUB_OUTPUT
           fi
 
-      - name: Get Portainer EndpointId
-        id: endpoint
+      - name: Generate UUID
+        if: ${{ steps.get_stack_id.outputs.stack_id == '0' }}
+        id: uuid
         run: |
-          RESPONSE=$(curl -s -X GET "http://${{ vars.RPI4_IP }}:83/api/endpoints" \
-            -H "Authorization: Bearer ${{ steps.auth.outputs.token }}")
-          ENDPOINT_ID=$(echo "$RESPONSE" | jq -r '.[] | select(.Name=="local") | .Id')
-          echo "endpoint_id=$ENDPOINT_ID" >> $GITHUB_OUTPUT
+          echo "::set-output name=uuid::$(uuidgen)"
 
       - name: Create Stack from GitHub
         if: ${{ steps.get_stack_id.outputs.stack_id == '0' }}
@@ -100,7 +116,7 @@ jobs:
                "AutoUpdate": {
                               "forcePullImage": true,
                               "forceUpdate": true,
-                              "Webhook": "e56041a2-75f6-4a10-85dc-c69424de631e"
+                              "Webhook": "${{ steps.uuid.outputs.uuid }}"
                              },
                "Env": [
                        {
@@ -211,7 +227,7 @@ jobs:
                   "dns":{
                       "piholePTR":"Hostname",
                       "domain": {
-                                  "name": "14monarch.local",
+                                  "name": "${{ inputs.subdomain }}.local",
                                   "local": true
                                 },
                       "upstreams": [
@@ -222,13 +238,13 @@ jobs:
                       "listeningMode": "single",
                       "revServers":["true,192.168.0.0/24,192.168.0.1,local"],
                       "hosts":[
-                              "192.168.0.1 tplink.14monarch.local",
-                              "${{ vars.RPI4_IP }} pihole.14monarch.local",
-                              "${{ vars.RPI4_IP }} nginx.14monarch.local",
-                              "${{ vars.RPI4_IP }} portainer.14monarch.local",
-                              "${{ vars.E7270_IP }} nextcloud.14monarch.local",
-                              "${{ vars.RPI4_IP }} adminer.14monarch.local",
-                              "${{ vars.RPI4_IP }} pih0le.14monarch.local"
+                              "192.168.0.1 tplink.${{ inputs.subdomain }}.local",
+                              "${{ vars.RPI4_IP }} pihole.${{ inputs.subdomain }}.local",
+                              "${{ vars.RPI4_IP }} nginx.${{ inputs.subdomain }}.local",
+                              "${{ vars.RPI4_IP }} portainer.${{ inputs.subdomain }}.local",
+                              "${{ vars.E7270_IP }} nextcloud.${{ inputs.subdomain }}.local",
+                              "${{ vars.RPI4_IP }} adminer.${{ inputs.subdomain }}.local",
+                              "${{ vars.RPI4_IP }} pih0le.${{ inputs.subdomain }}.local"
                               ]
                            },                          
                   "dhcp": {
